import CertificateDatabaseKeys from "@/database/Certificates/CertificateDatabaseKeys";
import RoleDatabaseKeys from "@/database/Roles/RoleDatabaseKeys";
import SkillDatabaseKeys from "@/database/Skills/SkillDatabaseKeys";
import ExperienceCategoriesEnum from "@/enums/Experience/ExperienceCategoriesEnum";
import ExperienceTypeEnum from "@/enums/Experience/ExperienceTypeEnum";
import RoleInterface from "@/database/Roles/RoleInterface";
import CompanyDatabaseKeys from "../Companies/CompanyDatabaseKeys";

const rolesMap: Database<RoleInterface> = {
  [RoleDatabaseKeys.Associate]: {
    name: "Associate",
    category: ExperienceCategoriesEnum.Software,
    type: ExperienceTypeEnum.Professional,
    skills: [
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.TypeScript,
      SkillDatabaseKeys.ReactJS,
      SkillDatabaseKeys.NodeJs,
      SkillDatabaseKeys.ExpressJS,
      SkillDatabaseKeys.CSS,
      SkillDatabaseKeys.HTML,
      SkillDatabaseKeys.Java,
      SkillDatabaseKeys.ObjectOrientedProgramming,
      SkillDatabaseKeys.REST,
      SkillDatabaseKeys.Azure_Datalake,
      SkillDatabaseKeys.APIs,
      SkillDatabaseKeys.PostgreSQL,
      SkillDatabaseKeys.MongoDB,
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.NonRelationalDatabases,
      SkillDatabaseKeys.ContinuousDelivery,
      SkillDatabaseKeys.IntegrationManagement,
      SkillDatabaseKeys.ContinuousDeployment,
      SkillDatabaseKeys.Git,
      SkillDatabaseKeys.Azure,
      SkillDatabaseKeys.Communication,
      SkillDatabaseKeys.Teamwork,
      SkillDatabaseKeys.ProblemSolving,
      SkillDatabaseKeys.CriticalThinking,
      SkillDatabaseKeys.Adaptability,
      SkillDatabaseKeys.TimeManagement,
      SkillDatabaseKeys.RiskManagement,
      SkillDatabaseKeys.StakeholderManagement,
      SkillDatabaseKeys.ScopeManagement,
      SkillDatabaseKeys.QualityManagement,
    ],
    startDate: "January 2025",
    endDate: "Present",
    relatedMaterials: [],
    company: CompanyDatabaseKeys.Cognizant,
  },
  [RoleDatabaseKeys.ProgrammerAnalyst]: {
    name: "Programmer Analyst",
    category: ExperienceCategoriesEnum.Software,
    type: ExperienceTypeEnum.Professional,
    skills: [
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.TypeScript,
      SkillDatabaseKeys.ReactJS,
      SkillDatabaseKeys.NodeJs,
      SkillDatabaseKeys.ExpressJS,
      SkillDatabaseKeys.NextJS,
      SkillDatabaseKeys.NextAuth,
      SkillDatabaseKeys.PostgreSQL,
      SkillDatabaseKeys.MongoDB,
      SkillDatabaseKeys.REST,
      SkillDatabaseKeys.CSS,
      SkillDatabaseKeys.HTML,
      SkillDatabaseKeys.APIs,
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.ObjectOrientedProgramming,
      SkillDatabaseKeys.Azure_Datalake,
      SkillDatabaseKeys.Azure_Databricks,
      SkillDatabaseKeys.RelationalDatabases,
      SkillDatabaseKeys.NonRelationalDatabases,
      SkillDatabaseKeys.ContinuousDelivery,
      SkillDatabaseKeys.ContinuousDeployment,
      SkillDatabaseKeys.Git,
      SkillDatabaseKeys.Communication,
      SkillDatabaseKeys.Teamwork,
      SkillDatabaseKeys.ProblemSolving,
      SkillDatabaseKeys.CriticalThinking,
      SkillDatabaseKeys.Adaptability,
      SkillDatabaseKeys.TimeManagement,
      SkillDatabaseKeys.RiskManagement,
      SkillDatabaseKeys.StakeholderManagement,
      SkillDatabaseKeys.QualityManagement,
    ],
    startDate: "September 2022",
    endDate: "December 2024",
    relatedMaterials: [
      CertificateDatabaseKeys.AzureAIFundamentals,
      CertificateDatabaseKeys.AzureAdministratorAssociate,
      CertificateDatabaseKeys.AzureDataEngineerAssociate,
    ],

    company: CompanyDatabaseKeys.Cognizant,
  },
  [RoleDatabaseKeys.ProgrammerAnalystTrainee]: {
    name: "Programmer Analyst Trainee",
    category: ExperienceCategoriesEnum.Software,
    type: ExperienceTypeEnum.Professional,
    company: CompanyDatabaseKeys.Cognizant,
    startDate: "September 2021",
    endDate: "September 2022",
    skills: [
      SkillDatabaseKeys.JavaScript,
      SkillDatabaseKeys.NodeJs,
      SkillDatabaseKeys.Azure_CosmosDB,
      SkillDatabaseKeys.Mongoose,
      SkillDatabaseKeys.CSS,
      SkillDatabaseKeys.HTML,
      SkillDatabaseKeys.Python,
      SkillDatabaseKeys.Java,
      SkillDatabaseKeys.Communication,
      SkillDatabaseKeys.Teamwork,
      SkillDatabaseKeys.ProblemSolving,
      SkillDatabaseKeys.CriticalThinking,
      SkillDatabaseKeys.Adaptability,
      SkillDatabaseKeys.TimeManagement,
      SkillDatabaseKeys.RiskManagement,
      SkillDatabaseKeys.ScopeManagement,
    ],
    relatedMaterials: [
      CertificateDatabaseKeys.AzureDataFundamentals,
      CertificateDatabaseKeys.AzureFundamentals,
      CertificateDatabaseKeys.CognizantGenAIBasics,
      CertificateDatabaseKeys.CognizantPysparkIntermediate,
    ],
  },
  [RoleDatabaseKeys.Intern]: {
    name: "Intern, Trainee",
    archived: true,
    category: ExperienceCategoriesEnum.Mechanical,
    type: ExperienceTypeEnum.Training,
    company: CompanyDatabaseKeys.DSP,
    startDate: "February 2020",
    endDate: "February 2020",
    skills: [
      SkillDatabaseKeys.Mechanics,
      SkillDatabaseKeys.Communication,
      SkillDatabaseKeys.Teamwork,
      SkillDatabaseKeys.ProblemSolving,
      SkillDatabaseKeys.CriticalThinking,
      SkillDatabaseKeys.Adaptability,
      SkillDatabaseKeys.TimeManagement,
      SkillDatabaseKeys.RiskManagement,
      SkillDatabaseKeys.StakeholderManagement,
      SkillDatabaseKeys.ScopeManagement,
      SkillDatabaseKeys.QualityManagement,
    ],
  },
};

export const roleDatabaseKeys: RoleDatabaseKeys[] = Object.keys(
  rolesMap
) as RoleDatabaseKeys[];

const rolesDatabase: Database<RoleInterface> = rolesMap;

export default rolesDatabase;
